# Generated by Django 2.1.4 on 2018-12-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('measure', models.CharField(choices=[('cl', 'centiliter'), ('lt', 'liter'), ('gr', 'gram'), ('kg', 'kilogram')], default='gr', max_length=10, verbose_name='measure')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='price')),
            ],
        ),
    ]
