# Generated by Django 2.1.4 on 2018-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='article_number',
            field=models.IntegerField(default=0, verbose_name='article number'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price (€)'),
        ),
    ]
