# Generated by Django 2.1.4 on 2018-12-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20181230_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='article_number',
        ),
    ]
